data_sets:
    - name: DfMcm5
      paired: True
      path: FASTQ/controls/Df-Mcm5/
      readsfile1: Df-Mcm5.R1.fq
      readsfile2: Df-Mcm5.R2.fq
      experimental: control
      source: dannyMiller
      subgroups: [all,control]
    - name: mcm5-01
      paired: True
      path: FASTQ/controls/mcm5-01/
      readsfile1: mcm5-01.R1.fq
      readsfile2: mcm5-01.R2.fq
      experimental: control
      source: dannyMiller
      subgroups: [all,control]
    - name: mcm5-02
      paired: True
      path: FASTQ/controls/mcm5-02/
      readsfile1: mcm5-02.R1.fq
      readsfile2: mcm5-02.R2.fq
      experimental: control
      source: dannyMiller
      subgroups: [all,control]
    - name: mcm5-03
      paired: True
      path: FASTQ/controls/mcm5-03/
      readsfile1: mcm5-03.R1.fq
      readsfile2: mcm5-03.R2.fq
      experimental: control
      source: dannyMiller
      subgroups: [all,control]
    - name: mcm5-04
      paired: True
      path: FASTQ/controls/mcm5-04/
      readsfile1: mcm5-04.R1.fq
      readsfile2: mcm5-04.R2.fq
      experimental: control
      source: dannyMiller
      subgroups: [all,control]
    - name: mcm5-05
      paired: True
      path: FASTQ/controls/mcm5-05/
      readsfile1: mcm5-05.R1.fq
      readsfile2: mcm5-05.R2.fq
      experimental: control
      source: dannyMiller
      subgroups: [all,control]
    - name: mcm5-06
      paired: True
      path: FASTQ/controls/mcm5-06/
      readsfile1: mcm5-06.R1.fq
      readsfile2: mcm5-06.R2.fq
      experimental: control
      source: dannyMiller
      subgroups: [all,control]
    - name: mcm5-07
      paired: True
      path: FASTQ/controls/mcm5-07/
      readsfile1: mcm5-07.R1.fq
      readsfile2: mcm5-07.R2.fq
      experimental: control
      source: dannyMiller
      subgroups: [all,control]
    - name: mcm5-08
      paired: True
      path: FASTQ/controls/mcm5-08/
      readsfile1: mcm5-08.R1.fq
      readsfile2: mcm5-08.R2.fq
      experimental: control
      source: dannyMiller
      subgroups: [all,control]
    - name: mcm5-09
      paired: True
      path: FASTQ/controls/mcm5-09/
      readsfile1: mcm5-09.R1.fq
      readsfile2: mcm5-09.R2.fq
      experimental: control
      source: dannyMiller
      subgroups: [all,control]
    - name: mcm5-10
      paired: True
      path: FASTQ/controls/mcm5-10/
      readsfile1: mcm5-10.R1.fq
      readsfile2: mcm5-10.R2.fq
      experimental: control
      source: dannyMiller
      subgroups: [all,control]
    - name: mcm5-11
      paired: True
      path: FASTQ/controls/mcm5-11/
      readsfile1: mcm5-11.R1.fq
      readsfile2: mcm5-11.R2.fq
      experimental: control
      source: dannyMiller
      subgroups: [all,control]
    - name: mcm5-12
      paired: True
      path: FASTQ/controls/mcm5-12/
      readsfile1: mcm5-12.R1.fq
      readsfile2: mcm5-12.R2.fq
      experimental: control
      source: dannyMiller
      subgroups: [all,control]
    - name: mcm5-13
      paired: True
      path: FASTQ/controls/mcm5-13/
      readsfile1: mcm5-13.R1.fq
      readsfile2: mcm5-13.R2.fq
      experimental: control
      source: dannyMiller
      subgroups: [all,control]
    - name: mcm5-14
      paired: True
      path: FASTQ/controls/mcm5-14/
      readsfile1: mcm5-14.R1.fq
      readsfile2: mcm5-14.R2.fq
      experimental: control
      source: dannyMiller
      subgroups: [all,control]
    - name: mcm5-15
      paired: True
      path: FASTQ/controls/mcm5-15/
      readsfile1: mcm5-15.R1.fq
      readsfile2: mcm5-15.R2.fq
      experimental: control
      source: dannyMiller
      subgroups: [all,control]
    - name: mcm5-16
      paired: True
      path: FASTQ/controls/mcm5-16/
      readsfile1: mcm5-16.R1.fq
      readsfile2: mcm5-16.R2.fq
      experimental: control
      source: dannyMiller
      subgroups: [all,control]
    - name: mcm5-17
      paired: True
      path: FASTQ/controls/mcm5-17/
      readsfile1: mcm5-17.R1.fq
      readsfile2: mcm5-17.R2.fq
      experimental: control
      source: dannyMiller
      subgroups: [all,control]
    - name: mcm5-18
      paired: True
      path: FASTQ/controls/mcm5-18/
      readsfile1: mcm5-18.R1.fq
      readsfile2: mcm5-18.R2.fq
      experimental: control
      source: dannyMiller
      subgroups: [all,control]
    - name: mcm5-19
      paired: True
      path: FASTQ/controls/mcm5-19/
      readsfile1: mcm5-19.R1.fq
      readsfile2: mcm5-19.R2.fq
      experimental: control
      source: dannyMiller
      subgroups: [all,control]
    - name: mcm5-20
      paired: True
      path: FASTQ/controls/mcm5-20/
      readsfile1: mcm5-20.R1.fq
      readsfile2: mcm5-20.R2.fq
      experimental: control
      source: dannyMiller
      subgroups: [all,control]
    - name: mcm5-21
      paired: True
      path: FASTQ/controls/mcm5-21/
      readsfile1: mcm5-21.R1.fq
      readsfile2: mcm5-21.R2.fq
      experimental: control
      source: dannyMiller
      subgroups: [all,control]
    - name: mcm5-22
      paired: True
      path: FASTQ/controls/mcm5-22/
      readsfile1: mcm5-22.R1.fq
      readsfile2: mcm5-22.R2.fq
      experimental: control
      source: dannyMiller
      subgroups: [all,control]
    - name: mcm5-23
      paired: True
      path: FASTQ/controls/mcm5-23/
      readsfile1: mcm5-23.R1.fq
      readsfile2: mcm5-23.R2.fq
      experimental: control
      source: dannyMiller
      subgroups: [all,control]
    - name: mcm5-24
      paired: True
      path: FASTQ/controls/mcm5-24/
      readsfile1: mcm5-24.R1.fq
      readsfile2: mcm5-24.R2.fq
      experimental: control
      source: dannyMiller
      subgroups: [all,control]
    - name: mcm5-25
      paired: True
      path: FASTQ/controls/mcm5-25/
      readsfile1: mcm5-25.R1.fq
      readsfile2: mcm5-25.R2.fq
      experimental: control
      source: dannyMiller
      subgroups: [all,control]
    - name: mcm5-26
      paired: True
      path: FASTQ/controls/mcm5-26/
      readsfile1: mcm5-26.R1.fq
      readsfile2: mcm5-26.R2.fq
      experimental: control
      source: dannyMiller
      subgroups: [all,control]
    - name: mcm5-27
      paired: True
      path: FASTQ/controls/mcm5-27/
      readsfile1: mcm5-27.R1.fq
      readsfile2: mcm5-27.R2.fq
      experimental: control
      source: dannyMiller
      subgroups: [all,control]
    - name: mcm5-28
      paired: True
      path: FASTQ/controls/mcm5-28/
      readsfile1: mcm5-28.R1.fq
      readsfile2: mcm5-28.R2.fq
      experimental: control
      source: dannyMiller
      subgroups: [all,control]
    - name: Mcm5-A7
      paired: True
      path: FASTQ/controls/Mcm5-A7/
      readsfile1: Mcm5-A7.R1.fq
      readsfile2: Mcm5-A7.R2.fq
      experimental: control
      source: dannyMiller
      subgroups: [all,control]


reference_genomes:
    - name: dm6
      species: drosophila melanogaster
      path: /proj/cdjones_lab/Genomics_Data_Commons/genomes/drosophila_melanogaster/dm6.fa
      fai: /proj/cdjones_lab/Genomics_Data_Commons/genomes/drosophila_melanogaster/dm6.fa.fai
      source: UCSC Genome Browser
